swagger: "2.0"
# Definições de segurança
securityDefinitions:
  basicAuth:
    type: basic
# Aplicação da segurança
security:
  - basicAuth: []
info:
  description: "Esta é a API Dipteron.  Você pode encontrar mais informações sobre em     Visiona - API Dipteron at [Visiona - API Dipteron](https://github.com/visiona-devteam/gcp-dipteron-api)."
  version: "1.0.0"
  title: "Visiona - API Dipteron"
  termsOfService: ""
  contact:
    email: "daniel.oliveira@visionaespacial.com.br"
  license:
    name: "MIT License"
    url: "https://github.com/danielvisiona/api-dipteron-documents/blob/main/LICENSE"
host: "localhost:5000"
# basePath: "/"
tags:
- name: "area"
  description: "Gerenciamento de Áreas"
- name: "contrato"
  description: "Gerenciamento de Contratos"
- name: "servico"
  description: "Serviços"
- name: "user"
  description: "Gerenciamento de Usuários"
- name: "municipio"
  description: "Auxíliar - Cadastro de Áreas"
- name: "estado"
  description: "Auxíliar - Busca de Municípios"
- name: "variavel"
  description: "Auxíliar - Cadastro de Áreas"

schemes:
- "http"
paths:
# Áreas
  /area/create:
    post:
      tags:
      - "area"
      summary: "Área Criação"
      description: "Criação de novas áreas"
      operationId: "login"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data Area create"
        required: true
        schema:
          $ref: "#/definitions/Area"
      responses:
        default:
          description: "successful operation"
  /area/read:
    get:
      tags:
      - "area"
      summary: "Área Criação"
      description: "Criação de novas áreas"
      operationId: "login"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data Area create"
        required: true
        schema:
          $ref: "#/definitions/Area"
      responses:
        default:
          description: "successful operation"
# Municípios
  /municipio/read:
      get:
        tags:
        - "municipio"
        summary: "Municípios do Brasil"
        description: "Retornar os Municípios do Brasil para auxiliar cadastro das Áreas"
        operationId: "municipio-read"
        consumes:
        - "application/json"
        responses:
          default:
            description: "successful operation"
  /municipio/read/{ibge_cd}:
      get:
        tags:
        - "municipio"
        summary: "Município do Brasil"
        description: "Retornar um Município do Brasil para auxiliar cadastro das Áreas"
        operationId: "municipio-read-ibge_cd"
        consumes:
        - "application/json"
        parameters:
        - in: "path"
          name: "ibge_cd"
          type: "integer"
          required: True
          description: "Código IBGE do Município"
        responses:
          default:
            description: "successful operation"
# Estados
  /estado/read:
    get:
      tags:
      - "estado"
      summary: "Estados do Brasil"
      description: "Retornar os Estados do Brasil para auxiliar na busca dos Municípios"
      operationId: "estado-read"
      consumes:
      - "application/json"
      responses:
        default:
          description: "successful operation"
# Variáveis Meteorológicas
  /variavel/read:
    get:
      tags:
      - "variavel"
      summary: "Variáveis Meteorológicas"
      description: "Retornar as Variáveis Meteorológicas para auxiliar no cadastro das áreas"
      operationId: "variavel-read"
      consumes:
      - "application/json"
      responses:
        default:
          description: "successful operation"

definitions:
  Area:
    type: "object"
    properties:
      nome:
        type: "string"
        example: "Visiona - Campinas"
      ibge_id:
        type: "integer"
        example: 3509502
      contrato_id:
        type: "integer"
        example: 1
      variavel_meteorologica:
        type: "string"
        description: "Definição da variável meteorológica - Pode ser duas ou mais separadas por vírgulas."
        example: "LST_Night_1km,LST_Day_1km,EVI_MODIS,NDVI_MODIS,Evapo_MODIS,CHIRPS"
    required:  
      - nome
      - ibge_id
      - contrato_id
      - variavel_meteorologica

externalDocs:
  description: "Saiba mais sobre"
  url: "https://github.com/danielvisiona/api-dipteron-documents"